### ISSUE TITLE
Why is -1 and Integer.MAX_VALUE returned in ArrayReaderImplementation.java?

### ISSUE THREAD

**Issue by ErdemT09** [altayhunoglu/algorithms#93]
https://github.com/altayhunoglu/algorithms/blob/master/src/main/java/algorithms/curated170/easy/ArrayReaderImplementation.java
In this code, the method "get" (line 9) returns -1 when the length of the array is 0 (lines 10-11) and Integer.MAX_VALUE when the index is out of bounds for the array (lines 13-14). Are these numbers arbitrary choices or do they have functional importance?

**Comment by altayhunoglu** [comment]
Hello Erdem,
This Java class is implemented for a question in LeetCode where they specified the parameters.
They have simulated an external service using a Java interface that contains a method to read from a hidden array.
So, I just implemented the interface in this class:

It is the question:

_**702. Search in a Sorted Array of Unknown Size**
 
Given an integer array sorted in ascending order, write a function to search target in nums.  If target exists, then return its index, otherwise return -1. However, the array size is unknown to you. You may only access the array using an ArrayReader interface, where ArrayReader.get(k) returns the element of the array at index k (0-indexed).

You may assume all integers in the array are less than 10000, and if you access the array out of bounds, ArrayReader.get will return 2147483647.

 

Example 1:

Input: array = [-1,0,3,5,9,12], target = 9
Output: 4
Explanation: 9 exists in nums and its index is 4
Example 2:

Input: array = [-1,0,3,5,9,12], target = 2
Output: -1
Explanation: 2 does not exist in nums so return -1_
